const API_URL="https://script.google.com/macros/s/AKfycbw2FH90KLUbPNrWS8PILmkUS9ml5-fnFkslfc4yeHJ7e9QfP2ST-MgAOKRsRz9M1GH_Ow/exec";
const state={lang:"ja",tasks:[],projects:[],members:[],reports:[],editing:null};
const demo={
 tasks:[{id:"T-001",name:"工程内不良データの分析",project:"不良低減PJ",owner:"山田",due:"2026-10-09",priority:"High",status:"In Progress",plannedHours:8},{id:"T-002",name:"測定機校正計画の承認",project:"計測管理",owner:"佐藤",due:"2026-10-10",priority:"High",status:"Not Started",plannedHours:6}],
 projects:[{id:"P-001",name:"工程内不良低減PJ",leader:"山田",deadline:"2026-11-20",progress:72,health:"On Track",desc:"組立工程の不良率を30%低減"},{id:"P-002",name:"新機種立上げ",leader:"佐藤",deadline:"2026-10-28",progress:48,health:"At Risk",desc:"量産開始までの品質保証準備"}],
 members:[{id:"M-001",name:"山田",email:"yamada@example.com",role:"Admin",capacity:40,active:true},{id:"M-002",name:"佐藤",email:"sato@example.com",role:"Manager",capacity:40,active:true},{id:"M-003",name:"鈴木",email:"suzuki@example.com",role:"Member",capacity:40,active:true}]
};
Object.assign(state,JSON.parse(JSON.stringify(demo)));
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
const fmt=v=>{const d=new Date(v);return Number.isNaN(d.getTime())?String(v||""):d.toISOString().slice(0,10)};
function toast(text){const e=$("#toast");e.textContent=text;e.classList.add("show");setTimeout(()=>e.classList.remove("show"),2600)}
function jsonp(action){return new Promise((resolve,reject)=>{const cb="qp_"+Date.now()+"_"+Math.random().toString(36).slice(2),s=document.createElement("script"),timer=setTimeout(()=>done(new Error("timeout")),10000);function done(err,data){clearTimeout(timer);delete window[cb];s.remove();err?reject(err):resolve(data)}window[cb]=d=>done(null,d);s.onerror=()=>done(new Error("connection"));s.src=API_URL+"?action="+action+"&callback="+cb;document.head.append(s)})}
function post(action,data){return fetch(API_URL,{method:"POST",mode:"no-cors",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify({action,data})})}
function status(s){return '<span class="status '+esc(String(s).toLowerCase().replaceAll(" ","-"))+'">'+esc(s)+"</span>"}
function priority(p){return '<span class="badge '+esc(String(p).toLowerCase())+'">'+esc(p)+"</span>"}
function renderAll(){renderDashboard();renderTasks();renderProjects();renderMembers()}
function renderDashboard(){
 const open=state.tasks.filter(x=>x.status!=="Done"),week=open.filter(x=>x.due<="2026-10-15");
 $("#openTaskCount").textContent=open.length;$("#dueCount").textContent=week.length;
 $("#priorityTaskList").innerHTML=open.slice(0,4).map(x=>'<div class="task-row"><i class="task-bar '+esc(x.priority.toLowerCase())+'"></i><div><strong>'+esc(x.name)+'</strong><small>'+esc(x.project)+" · "+esc(x.owner)+" · "+esc(x.due)+" · "+(Number(x.plannedHours)||4)+'h</small></div>'+priority(x.priority)+"</div>").join("")||"<p class='muted'>No open task</p>";
 $("#projectList").innerHTML=state.projects.map(x=>'<div class="project-item '+(x.health==="At Risk"?"danger":"")+'"><div class="project-meta"><b>'+esc(x.name)+'</b><small>'+x.progress+'%</small></div><div class="progress"><span style="width:'+x.progress+'%"></span></div><div class="project-meta"><small>'+esc(x.deadline)+'</small><b>'+esc(x.health)+'</b></div></div>').join("");
 const days=["Mon","Tue","Wed","Thu","Fri"],people=state.members.filter(m=>m.active!==false);
 $("#heatmap").innerHTML="<span></span>"+days.map(d=>"<span>"+d+"</span>").join("")+people.map(m=>{const h=open.filter(t=>t.owner===m.name).reduce((n,t)=>n+(Number(t.plannedHours)||4),0),cap=Number(m.capacity)||40,l=Math.max(1,Math.min(4,Math.ceil(h/(cap*.25))));return "<span title='"+h+"h / "+cap+"h'>"+esc(m.name)+"</span>"+days.map((_,i)=>"<i class='l"+(i?Math.max(1,l-1):l)+"'></i>").join("")}).join("");
}
function renderTasks(){
 const q=$("#taskSearch").value.toLowerCase(),f=$("#statusFilter").value;
 const list=state.tasks.filter(x=>(!q||Object.values(x).join(" ").toLowerCase().includes(q))&&(!f||x.status===f));
 $("#taskTable").innerHTML=list.map(x=>"<tr><td><b>"+esc(x.name)+"</b><br><small>"+esc(x.id)+(x.emergencyType?" · ⚠ "+esc(x.emergencyType):"")+"</small></td><td>"+esc(x.project)+"</td><td>"+esc(x.owner)+"</td><td>"+esc(x.due)+"<br><small>"+(Number(x.plannedHours)||4)+"h</small></td><td>"+priority(x.priority)+"</td><td>"+status(x.status)+"</td><td><button class='text-btn' data-edit='task' data-id='"+esc(x.id)+"'>Edit</button> <button class='text-btn danger-btn' data-delete='task' data-id='"+esc(x.id)+"'>Delete</button></td></tr>").join("")||"<tr><td colspan='7'>No task found.</td></tr>";
 bindRowActions();
}
function renderProjects(){$("#projectCards").innerHTML=state.projects.map(x=>"<article class='panel project-card'><span class='status "+(x.health==="At Risk"?"not-started":"done")+"'>"+esc(x.health)+"</span><h3>"+esc(x.name)+"</h3><p>"+esc(x.desc)+"</p><div class='progress'><span style='width:"+x.progress+"%'></span></div><div class='card-footer'><span>"+x.progress+"% complete</span><span>"+esc(x.deadline)+"</span></div><div class='card-footer'><span>Owner: "+esc(x.leader)+"</span><span><button class='text-btn' data-edit='project' data-id='"+esc(x.id)+"'>Edit</button> <button class='text-btn danger-btn' data-delete='project' data-id='"+esc(x.id)+"'>Delete</button></span></div></article>").join("");bindRowActions()}
function renderMembers(){const body=$("#memberTable");if(!body)return;const open=state.tasks.filter(x=>x.status!=="Done");body.innerHTML=state.members.map(m=>{const work=open.filter(t=>t.owner===m.name).reduce((n,t)=>n+(Number(t.plannedHours)||4),0),cap=Number(m.capacity)||40;return "<tr><td><b>"+esc(m.name)+"</b><br><small>"+esc(m.email)+"</small></td><td>"+esc(m.role)+"</td><td>"+cap+"h</td><td>"+work+"h</td><td>"+(work>cap?"<span class='badge high'>OVERLOAD</span>":"<span class='badge low'>OK</span>")+"</td><td><button class='text-btn' data-edit='member' data-id='"+esc(m.id)+"'>Edit</button> <button class='text-btn danger-btn' data-delete='member' data-id='"+esc(m.id)+"'>Delete</button></td></tr>"}).join("");bindRowActions()}
function bindRowActions(){$$("[data-edit]").forEach(b=>b.onclick=()=>openForm(b.dataset.edit,b.dataset.id));$$("[data-delete]").forEach(b=>b.onclick=()=>deleteItem(b.dataset.delete,b.dataset.id))}
function input(label,name,value="",type="text",required=true){return "<div class='field'><label>"+label+"</label><input name='"+name+"' type='"+type+"' value='"+esc(value)+"' "+(required?"required":"")+"></div>"}
function select(label,name,values,value){return "<div class='field'><label>"+label+"</label><select name='"+name+"'>"+values.map(v=>"<option "+(v===value?"selected":"")+">"+v+"</option>").join("")+"</select></div>"}
function formHtml(type,x={}){
 if(type==="task")return input("Task name", "name",x.name)+input("Project","project",x.project||"Ad-hoc")+select("Owner","owner",state.members.map(m=>m.name),x.owner||state.members[0]?.name||"")+input("Due date","due",x.due||"", "date")+input("Planned hours","plannedHours",x.plannedHours||4,"number")+select("Priority","priority",["Critical","High","Medium","Low"],x.priority||"Medium")+select("Status","status",["Not Started","In Progress","Done"],x.status||"Not Started")+select("Emergency type","emergencyType",["","Machine breakdown","Quality defect","Safety risk","Production stop"],x.emergencyType||"")+input("Machine / line / impact","impact",x.impact||"", "text",false);
 if(type==="project")return input("Project name","name",x.name)+input("Leader","leader",x.leader||state.members[0]?.name||"")+input("Deadline","deadline",x.deadline||"","date")+input("Progress %","progress",x.progress??0,"number")+select("Health","health",["On Track","At Risk"],x.health||"On Track")+input("Objective / KPI","desc",x.desc||"");
 if(type==="member")return input("Name","name",x.name)+input("Company email","email",x.email,"email")+select("Role","role",["Member","Manager","Admin"],x.role||"Member")+input("Capacity hours / week","capacity",x.capacity||40,"number")+select("Active","active",["TRUE","FALSE"],x.active===false?"FALSE":"TRUE");
 if(type==="report")return input("Work date","date",x.date||new Date().toISOString().slice(0,10),"date")+input("Worked hours","hours",x.hours||8,"number")+"<div class='field'><label>Work / issue / tomorrow plan</label><textarea name='content' required>"+esc(x.content||"")+"</textarea></div>";
}
function openForm(type,id){
 const collection=type==="task"?state.tasks:type==="project"?state.projects:type==="member"?state.members:state.reports;
 const item=id?collection.find(x=>x.id===id):{};
 state.editing={type,id};
 $("#modalTitle").textContent=(id?"Edit ":"New ")+type;
 $("#modalFields").innerHTML=formHtml(type,item);
 $("#entryModal").showModal();
}
async function saveModal(e){e.preventDefault();const data=Object.fromEntries(new FormData($("#entryForm")).entries()),{type,id}=state.editing||{};if(!type)return;
 const collection=type==="task"?state.tasks:type==="project"?state.projects:type==="member"?state.members:state.reports;
 const record=type==="task"?{id:id||"T-"+Date.now(),...data,plannedHours:Number(data.plannedHours||4)}:type==="project"?{id:id||"P-"+Date.now(),...data,progress:Number(data.progress||0)}:type==="member"?{id:id||"M-"+Date.now(),...data,capacity:Number(data.capacity||40),active:data.active!=="FALSE"}:{id:id||"R-"+Date.now(),...data};
 if(id){const i=collection.findIndex(x=>x.id===id);collection[i]=record;post("update"+type[0].toUpperCase()+type.slice(1),record)}else{collection.unshift(record);post("create"+type[0].toUpperCase()+type.slice(1),record)}
 $("#entryModal").close();state.editing=null;renderAll();toast("Saved successfully")}
function deleteItem(type,id){const name=(type==="task"?state.tasks:type==="project"?state.projects:state.members).find(x=>x.id===id)?.name||"this item";if(!confirm("Delete "+name+"?"))return;const key=type==="task"?"tasks":type==="project"?"projects":"members";state[key]=state[key].filter(x=>x.id!==id);post("delete"+type[0].toUpperCase()+type.slice(1),{id});renderAll();toast("Deleted")}
async function load(){try{const d=await jsonp("dashboard");if(d.tasks?.length)state.tasks=d.tasks.map(x=>({id:x["Task ID"],name:x["Task Name"],project:x.Project,owner:x.Owner,due:fmt(x["Due Date"]),priority:x.Priority,status:x.Status,plannedHours:Number(x["Planned Hours"])||4,emergencyType:x["Emergency Type"],impact:x["Machine / Line / Impact"]}));if(d.projects?.length)state.projects=d.projects.map(x=>({id:x["Project ID"],name:x["Project Name"],leader:x.Leader,deadline:fmt(x.Deadline),progress:Number(x["Progress %"])||0,health:x.Health,desc:x["Objective / KPI"]}));if(d.members?.length)state.members=d.members.map(x=>({id:x["Member ID"],name:x.Name,email:x.Email,role:x.Role,capacity:Number(x["Capacity Hours / Week"])||40,active:String(x.Active)!=="FALSE"}));renderAll()}catch(_){toast("Demo mode: backend belum dapat dibaca")}}
document.addEventListener("DOMContentLoaded",()=>{$("#today").textContent=new Date().toLocaleDateString("ja-JP",{year:"numeric",month:"long",day:"numeric",weekday:"long"});renderAll();load();$("#entryForm").addEventListener("submit",saveModal);$("#cancelBtn").onclick=()=>{$("#entryModal").close();state.editing=null};$("#taskSearch").oninput=renderTasks;$("#statusFilter").onchange=renderTasks;$$("[data-view]").forEach(b=>b.onclick=()=>{$$("[data-view]").forEach(x=>x.classList.remove("active"));b.classList.add("active");$$(".view").forEach(x=>x.classList.remove("active"));$("#"+b.dataset.view).classList.add("active")});$$("[data-new]").forEach(b=>b.onclick=()=>openForm(b.dataset.new));$("#saveReport").onclick=()=>openForm("report");$("#languageBtn").onclick=()=>toast("Japanese / English text can be expanded next");});
