const API_URL="https://script.google.com/macros/s/AKfycbw2FH90KLUbPNrWS8PILmkUS9ml5-fnFkslfc4yeHJ7e9QfP2ST-MgAOKRsRz9M1GH_Ow/exec";
const state={openProj:new Set(),detail:null,tasks:[],projects:[],members:[],reports:[],editing:null,language:"ja"};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
const fmt=v=>{if(typeof v==="string"&&/^\d{4}-\d{2}-\d{2}/.test(v))return v.slice(0,10);const d=new Date(v);if(Number.isNaN(d.getTime()))return String(v||"");const p=n=>String(n).padStart(2,"0");return d.getFullYear()+"-"+p(d.getMonth()+1)+"-"+p(d.getDate())};
const JA={
  priority:{Critical:"最優先",High:"高",Medium:"中",Low:"低"},
  status:{"Not Started":"未着手","In Progress":"進行中",Done:"完了"},
  health:{"On Track":"順調","At Risk":"要注意"},
  role:{Admin:"管理者",Manager:"マネージャー",Member:"メンバー"},
  emergency:{"":"なし","Machine breakdown":"設備故障","Quality defect":"品質不良","Safety risk":"安全リスク","Production stop":"生産停止"}
};
const EN={priority:{Critical:"Critical",High:"High",Medium:"Medium",Low:"Low"},status:{"Not Started":"Not started","In Progress":"In progress",Done:"Done"},health:{"On Track":"On track","At Risk":"At risk"},role:{Admin:"Admin",Manager:"Manager",Member:"Member"},emergency:{"":"None","Machine breakdown":"Machine breakdown","Quality defect":"Quality defect","Safety risk":"Safety risk","Production stop":"Production stop"}};
const label=(type,value)=>(state.language==="en"?EN:JA)[type]?.[value]??value??"";
const STATIC_EN={"品質管理生産技術部":"Quality Management & Production Engineering","品質管理ワークフロー":"Quality Management Workflow","ダッシュボード":"Dashboard","タスク":"Tasks","プロジェクト":"Projects","メンバー":"Members","スケジュール":"Schedule","進捗メモ（任意）":"Progress notes (optional)","メンバーKPI":"Member KPI","システム稼働中":"System online","本日の重点項目":"TODAY'S FOCUS","品質を守り、改善を前へ。":"Protect quality. Drive improvement.","優先度・期限・作業負荷を一画面で確認できます。":"Priorities, deadlines and workload in one view.","＋ 新規タスク":"＋ New task","⚠ 緊急対応":"⚠ Emergency response","未完了タスク":"Open tasks","現在対応中の作業":"Work currently in progress","今週の期限":"Due this week","期限を確認":"Review deadlines","プロジェクト健全性":"Project health","要確認":"Review needed","「要注意」を優先確認":"Prioritize at-risk projects","稼働中メンバー":"Active members","優先タスク":"Priority tasks","今日の優先順位":"Today's priorities","すべて見る":"View all","作業負荷ヒートマップ":"Workload heatmap","予定工数 / 週の容量":"Planned hours / weekly capacity","メンバー別作業負荷":"Workload by member","未完了タスクの予定工数 / 週の容量":"Open-task hours / weekly capacity","プロジェクト進捗":"Project progress","期限とリスクの確認":"Deadlines and risks","進捗メモ":"Progress notes","必要な時だけ記録":"Record only when needed","毎日提出は不要です。重要な進捗・問題だけ記録できます。":"No daily report required. Record important progress and issues.","進捗メモを追加":"Add progress note","通常作業と緊急対応を一元管理":"Manage regular and emergency work","＋ 新規プロジェクト":"＋ New project","改善活動・新規立上げの進捗":"Improvement and launch progress","役割、週の容量、作業負荷を管理":"Manage roles, capacity and workload","＋ メンバー追加":"＋ Add member","↓ CSVダウンロード":"↓ Download CSV"};
function translateStatic(){const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);let n;while(n=walker.nextNode()){const raw=n.nodeValue,trim=raw.trim();if(!trim)continue;if(state.language==="en"&&STATIC_EN[trim]){n._qpOriginal=raw;n.nodeValue=raw.replace(trim,STATIC_EN[trim])}else if(state.language==="ja"&&n._qpOriginal){n.nodeValue=n._qpOriginal;delete n._qpOriginal}}document.documentElement.lang=state.language==="en"?"en":"ja";const b=$("#languageToggle");if(b)b.textContent=state.language==="en"?"日本語":"EN";}
function toast(text){const e=$("#toast");e.textContent=text;e.classList.add("show");setTimeout(()=>e.classList.remove("show"),2600)}
function jsonp(action,attempt=1){return new Promise((resolve,reject)=>{const cb="qp_"+Date.now()+"_"+Math.random().toString(36).slice(2),s=document.createElement("script"),timer=setTimeout(()=>done(new Error("timeout")),30000);let finished=false;function done(err,data){if(finished)return;finished=true;clearTimeout(timer);window[cb]=()=>{};setTimeout(()=>{s.remove();delete window[cb]},60000);if(err){if(attempt<2)resolve(jsonp(action,attempt+1));else reject(err)}else resolve(data)}window[cb]=d=>done(null,d);s.onerror=()=>done(new Error("connection"));s.src=API_URL+"?action="+action+"&callback="+cb+"&_="+Date.now();document.head.append(s)})}
async function post(action,data){
 let res;
 try{res=await fetch(API_URL,{method:"POST",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify({action,data})})}
 catch(_){const e=new Error("backend unreachable");e.code="network";throw e}
 let out;try{out=await res.json()}catch(_){const e=new Error("invalid backend response");e.code="network";throw e}
 if(!out.ok){const e=new Error(out.error||"error");e.code=out.code||"error";throw e}
 return out}
function handleApiError(err){toast(err.code==="network"?"バックエンドに接続できません。デプロイ設定（アクセス: 全員）を確認してください。":"エラー: "+err.message)}
function status(s){return '<span class="status '+esc(String(s).toLowerCase().replaceAll(" ","-"))+'">'+esc(label("status",s))+"</span>"}
function priority(p){return '<span class="badge '+esc(String(p).toLowerCase())+'">'+esc(label("priority",p))+"</span>"}
function taskParticipants(t){return [...new Set([t.owner,...String(t.supportMembers||"").split("|")].map(x=>String(x||"").trim()).filter(Boolean))]}
function memberHours(name,tasks){return tasks.filter(t=>taskParticipants(t).includes(name)).reduce((total,t)=>total+(Number(t.plannedHours)||4)/Math.max(1,taskParticipants(t).length),0)}
function projectProgress(p){const tasks=state.tasks.filter(t=>t.project===p.name);if(!tasks.length)return Number(p.progress)||0;const total=tasks.reduce((n,t)=>n+(Number(t.plannedHours)||1),0);const done=tasks.filter(t=>t.status==="Done").reduce((n,t)=>n+(Number(t.plannedHours)||1),0);return total?Math.round(done/total*100):0}
function remainingInfo(date){if(!date)return {text:"期限未設定",className:""};const today=new Date();today.setHours(0,0,0,0);const due=new Date(date+"T00:00:00");if(Number.isNaN(due.getTime()))return {text:"期限未設定",className:""};const days=Math.ceil((due-today)/86400000);if(days<0)return {text:"期限超過 "+Math.abs(days)+"日",className:"late"};if(days===0)return {text:"本日期限",className:"urgent"};return {text:"残り "+days+"日",className:days<=3?"urgent":""}}
function renderAll(){renderDashboard();renderTasks();renderProjects();renderMembers();renderReports();renderKpi();translateStatic();if(state.detail&&$("#detailModal")&&$("#detailModal").open)renderMemberDetail()}
function renderDashboard(){
 const open=state.tasks.filter(x=>x.status!=="Done"),week=open.filter(x=>x.due&&x.due<=fmt(new Date(Date.now()+7*86400000)));
 $("#openTaskCount").textContent=open.length;$("#dueCount").textContent=week.length;
 const mc=$("#memberCount");if(mc)mc.textContent=state.members.filter(m=>m.active!==false).length;
 $("#priorityTaskList").innerHTML=open.slice(0,4).map(x=>'<div class="task-row"><i class="task-bar '+esc(x.priority.toLowerCase())+'"></i><div><strong>'+esc(x.name)+'</strong><small>'+esc(x.project)+" ・ "+esc(x.owner)+" ・ "+esc(x.due)+" ・ "+(Number(x.plannedHours)||4)+"時間</small></div>"+priority(x.priority)+"</div>").join("")||"<p class='muted'>未完了のタスクはありません。</p>";
 $("#projectList").innerHTML=state.projects.map(x=>{const progress=projectProgress(x),remaining=remainingInfo(x.deadline);return '<div class="project-item '+(x.health==="At Risk"?"danger":"")+'"><div class="project-meta"><b>'+esc(x.name)+'</b><small>'+progress+'%</small></div><div class="progress"><span style="width:'+progress+'%"></span></div><div class="project-meta"><small class="'+remaining.className+'">'+esc(remaining.text)+'</small><b>'+esc(label("health",x.health))+'</b></div></div>'}).join("")||"<p class='muted'>プロジェクトはありません。</p>";
 const days=["月","火","水","木","金"],people=state.members.filter(m=>m.active!==false);
 $("#heatmap").innerHTML="<span></span>"+days.map(d=>"<span>"+d+"</span>").join("")+people.map(m=>{const h=memberHours(m.name,open),cap=Number(m.capacity)||40,l=Math.max(1,Math.min(4,Math.ceil(h/(cap*.25))));return "<span title='"+h+"時間 / "+cap+"時間'>"+esc(m.name)+"</span>"+days.map((_,i)=>"<i class='l"+(i?Math.max(1,l-1):l)+"'></i>").join("")}).join("")||"<p class='muted'>メンバーを登録してください。</p>";
 const workload=$("#workloadList");if(workload)workload.innerHTML=people.map(m=>{const h=memberHours(m.name,open),cap=Number(m.capacity)||40,p=Math.min(100,Math.round(h/cap*100));const tone=h>cap?"over":p>=80?"warn":"";return "<div class='workload-row'><div><b>"+esc(m.name)+"</b><small>"+Math.round(h*10)/10+"h / "+cap+"h</small></div><div class='workload-meter'><i class='"+tone+"' style='width:"+p+"%'></i></div><span class='"+tone+"'>"+p+"%</span></div>"}).join("")||"<p class='muted'>メンバーを登録してください。</p>";
}
function renderTasks(){
 const q=$("#taskSearch").value.toLowerCase(),f=$("#statusFilter").value;
 const list=state.tasks.filter(x=>(!q||Object.values(x).join(" ").toLowerCase().includes(q))&&(!f||x.status===f));
 $("#taskTable").innerHTML=list.map(x=>"<tr><td><b>"+esc(x.name)+"</b><br><small>"+esc(x.id)+(x.emergencyType?" ・ ⚠ "+esc(label("emergency",x.emergencyType)):"")+"</small></td><td>"+esc(x.project)+"</td><td>"+esc(x.owner)+"</td><td>"+esc(x.due)+"<br><small>"+(Number(x.plannedHours)||4)+"時間</small></td><td>"+priority(x.priority)+"</td><td>"+statusSelect(x)+"</td><td><button class='text-btn' data-edit='task' data-id='"+esc(x.id)+"'>編集</button> <button class='text-btn danger-btn' data-delete='task' data-id='"+esc(x.id)+"'>削除</button></td></tr>").join("")||"<tr><td colspan='7'>タスクはありません。</td></tr>";
 bindRowActions();
}
function renderProjects(){$("#projectCards").innerHTML=state.projects.map(x=>{const progress=projectProgress(x),remaining=remainingInfo(x.deadline),taskCount=state.tasks.filter(t=>t.project===x.name).length;return "<article class='panel project-card'><div class='project-card-top'>"+healthSelect(x)+"<span class='notify-chip'>🔔 責任者へ通知</span></div><h3>"+esc(x.name)+"</h3><p>"+esc(x.desc)+"</p><div class='project-stat-grid'><div><small>進捗</small><b>"+progress+"%</b></div><div><small>残り</small><b class='"+remaining.className+"'>"+esc(remaining.text)+"</b></div><div><small>タスク</small><b>"+taskCount+"件</b></div></div><div class='progress'><span style='width:"+progress+"%'></span></div><div class='project-load'><small>プロジェクト内の負荷（予定工数）</small><div class='load-people'>"+state.members.map(m=>({name:m.name,hours:memberHours(m.name,state.tasks.filter(t=>t.project===x.name&&t.status!=="Done"))})).filter(v=>v.hours>0).map(v=>"<span>"+esc(v.name)+" <b>"+Math.round(v.hours*10)/10+"h</b></span>").join("")+"</div></div>"+projectTaskList(x)+"<div class='notification-strip'><span>通知先</span><b>"+esc(x.leader||"未設定")+"</b><small>期限3日前・要注意時にメール</small></div><div class='card-footer'><span>期限 "+esc(x.deadline)+"</span><span><button class='text-btn' data-edit='project' data-id='"+esc(x.id)+"'>編集・更新</button> <button class='text-btn danger-btn' data-delete='project' data-id='"+esc(x.id)+"'>削除</button></span></div></article>"}).join("")||"<p class='muted'>プロジェクトはありません。</p>";bindRowActions()}
function renderMembers(){const body=$("#memberTable");if(!body)return;const open=state.tasks.filter(x=>x.status!=="Done");body.innerHTML=state.members.map(m=>{const work=memberHours(m.name,open),cap=Number(m.capacity)||40;return "<tr><td><b>"+esc(m.name)+"</b><br><small>"+esc(m.email)+"</small></td><td>"+esc(label("role",m.role))+"</td><td>"+cap+"時間</td><td>"+work+"時間</td><td>"+(work>cap?"<span class='badge high'>過負荷</span>":"<span class='badge low'>適正</span>")+"</td><td><button class='text-btn' data-member-detail='"+esc(m.name)+"'>詳細</button> <button class='text-btn' data-edit='member' data-id='"+esc(m.id)+"'>編集</button> <button class='text-btn danger-btn' data-delete='member' data-id='"+esc(m.id)+"'>削除</button></td></tr>"}).join("")||"<tr><td colspan='6'>メンバーはありません。</td></tr>";bindRowActions()}
function renderReports(){const body=$("#reportTable");if(!body)return;const taskName=id=>state.tasks.find(t=>t.id===id)?.name||"—";body.innerHTML=state.reports.slice().sort((a,b)=>String(b.date).localeCompare(String(a.date))).map(r=>"<tr><td><b>"+esc(r.date)+"</b></td><td>"+esc(r.member||"—")+"</td><td><span class='task-link'>"+esc(taskName(r.taskId))+"</span></td><td><b>"+(Number(r.hours)||0)+"時間</b></td><td><p class='report-content'>"+esc(r.content||"—")+"</p>"+(r.issues?"<small class='risk-line'>⚑ "+esc(r.issues)+"</small>":"")+"</td></tr>").join("")||"<tr><td colspan='5'>進捗メモはまだありません。重要な進捗・問題が出た時に追加してください。</td></tr>"} 
function renderKpi(){const root=$("#kpiCards");if(!root)return;const today=new Date();today.setHours(23,59,59,999);const active=state.members.filter(m=>m.active!==false);root.innerHTML=active.map(m=>{const mine=state.tasks.filter(t=>taskParticipants(t).includes(m.name)),done=mine.filter(t=>t.status==="Done"),open=mine.filter(t=>t.status!=="Done"),work=memberHours(m.name,open),cap=Number(m.capacity)||40,reports=state.reports.filter(r=>r.member===m.name||r.memberEmail===m.email),timed=done.filter(t=>t.completedAt&&t.due),onTime=timed.filter(t=>new Date(t.completedAt)<=new Date(t.due+"T23:59:59")).length,rate=timed.length?Math.round(onTime/timed.length*100):null,issues=reports.filter(r=>r.issues&&r.issues!=="なし").length,load=Math.min(100,Math.round(work/cap*100));return "<article class='kpi-card' data-member-detail='"+esc(m.name)+"' title='クリックで詳細' style='cursor:pointer'><div class='kpi-person'><div class='member-initial'>"+esc(m.name.slice(0,1))+"</div><div><h3>"+esc(m.name)+"</h3><span>"+esc(label("role",m.role))+" ・ "+(work>cap?"<b class='overload'>過負荷</b>":"稼働は適正")+"</span></div></div><div class='kpi-stats'><div><b>"+done.length+"</b><span>完了タスク</span></div><div><b>"+(rate===null?"—":rate+"%")+"</b><span>期限遵守</span></div><div><b>"+reports.length+"</b><span>任意メモ</span></div></div><div class='load-row'><span>現在の負荷</span><b>"+work+" / "+cap+" 時間</b></div><div class='load-bar'><i class='"+(work>cap?"hot":"")+"' style='width:"+load+"%'></i></div><div class='kpi-footer'><span>"+(issues?"⚑ リスク報告 "+issues+"件":"✓ リスク報告なし")+"</span><span>詳細を見る →</span></div></article>"}).join("")||"<p class='muted'>メンバーを登録するとKPIが表示されます。</p>"}
function bindRowActions(){$$("[data-edit]").forEach(b=>b.onclick=()=>openForm(b.dataset.edit,b.dataset.id));$$("[data-delete]").forEach(b=>b.onclick=()=>deleteItem(b.dataset.delete,b.dataset.id))}
function input(labelText,name,value="",type="text",required=true){return "<div class='field'><label>"+labelText+"</label><input name='"+name+"' type='"+type+"' value='"+esc(value)+"' "+(required?"required":"")+"></div>"}
function select(labelText,name,values,value){return "<div class='field'><label>"+labelText+"</label><select name='"+name+"'>"+values.map(v=>{const actual=typeof v==="string"?v:v.value,text=typeof v==="string"?v:v.label;return "<option value='"+esc(actual)+"' "+(actual===value?"selected":"")+">"+esc(text)+"</option>"}).join("")+"</select></div>"}
const choices=(type,values)=>values.map(value=>({value,label:label(type,value)}));
function formHtml(type,x={}){
 if(type==="task"){const common="共通業務・臨時対応";const projectOptions=[...state.projects.map(p=>p.name),common];const current=projectOptions.includes(x.project)?x.project:(x.project||state.projects[0]?.name||common);const selectedProject=state.projects.find(p=>p.name===current);const helpers=String(x.supportMembers||"").split("|");const supportHtml="<div class='field'><label>支援メンバー（任意・複数選択可）</label><div class='support-checks'>"+state.members.filter(m=>m.active!==false).map(m=>"<label><input type='checkbox' name='supportMembers' value='"+esc(m.name)+"' "+(helpers.includes(m.name)?"checked":"")+"> "+esc(m.name)+"</label>").join("")+"</div></div>";return input("タスク名","name",x.name)+select("プロジェクト","project",projectOptions,current)+"<p class='field-help'>① プロジェクトを選択　② 主担当者を選択　③ 必要なら支援メンバーを追加。工数は担当者間で均等配分されます。</p>"+select("主担当者","owner",state.members.map(m=>m.name),x.owner||selectedProject?.leader||state.members[0]?.name||"")+supportHtml+input("期限","due",x.due||"","date")+input("予定工数（時間）","plannedHours",x.plannedHours||4,"number")+select("優先度","priority",choices("priority",["Critical","High","Medium","Low"]),x.priority||"Medium")+select("状態","status",choices("status",["Not Started","In Progress","Done"]),x.status||"Not Started")+select("緊急対応の種類","emergencyType",choices("emergency",["","Machine breakdown","Quality defect","Safety risk","Production stop"]),x.emergencyType||"")+input("設備・ライン・影響内容","impact",x.impact||"","text",false);}
 if(type==="project")return input("プロジェクト名","name",x.name)+select("責任者", "leader",state.members.map(m=>m.name),x.leader||state.members[0]?.name||"")+input("期限","deadline",x.deadline||"","date")+input("初期進捗率（%）","progress",x.progress??0,"number")+"<p class='field-help'>タスクを登録後の進捗率は、完了タスクの予定工数から自動計算されます。</p>"+select("健全性","health",choices("health",["On Track","At Risk"]),x.health||"On Track")+input("目的・KPI","desc",x.desc||"");
 if(type==="member")return input("氏名","name",x.name)+input("会社メールアドレス","email",x.email,"email")+select("役割","role",choices("role",["Member","Manager","Admin"]),x.role||"Member")+input("週の作業可能時間","capacity",x.capacity||40,"number")+select("在籍状況","active",[{value:"TRUE",label:"有効"},{value:"FALSE",label:"無効"}],x.active===false?"FALSE":"TRUE");
 if(type==="report")return select("記録者","member",state.members.filter(m=>m.active!==false).map(m=>m.name),x.member||state.members[0]?.name||"")+input("記録日","date",x.date||fmt(new Date()),"date")+select("関連タスク","taskId",[{value:"",label:"タスクを選択（任意）"},...state.tasks.map(t=>({value:t.id,label:t.name+"（"+t.id+"）"}))],x.taskId||"")+input("実績工数（時間）","hours",x.hours||8,"number")+"<div class='field'><label>今日の実績</label><textarea name='content' required placeholder='完了した作業・確認した内容を入力'>"+esc(x.content||"")+"</textarea></div><div class='field'><label>問題・リスク</label><textarea name='issues' placeholder='なければ「なし」と入力'>"+esc(x.issues||"")+"</textarea></div><div class='field'><label>明日の予定</label><textarea name='tomorrow' placeholder='次に行う作業を入力'>"+esc(x.tomorrow||"")+"</textarea></div>";
}
function projectDeadlineGuard_(){const projectSelect=$('#modalFields [name="project"]'),dueInput=$('#modalFields [name="due"]'),ownerSelect=$('#modalFields [name="owner"]');if(!projectSelect||!dueInput)return;const apply=()=>{const p=state.projects.find(x=>x.name===projectSelect.value);if(!p?.deadline){dueInput.removeAttribute('max');return}dueInput.max=p.deadline;if(!dueInput.value||dueInput.value>p.deadline)dueInput.value=p.deadline;if(ownerSelect&&p.leader)ownerSelect.value=p.leader};projectSelect.onchange=apply;apply()}
function openForm(type,id,prefill){
 const emergency=type==="emergency";if(emergency){type="task";id=null}
 const collection=type==="task"?state.tasks:type==="project"?state.projects:type==="member"?state.members:state.reports;
 const item=id?collection.find(x=>x.id===id):(emergency?{priority:"Critical",status:"In Progress",emergencyType:"Machine breakdown",plannedHours:4}:(prefill||{}));
 state.editing={type,id};
 const title={task:"タスク",project:"プロジェクト",member:"メンバー",report:"進捗メモ"}[type];
 $("#modalTitle").textContent=emergency?"緊急対応の登録":(id?"編集：":"新規登録：")+title;
 $("#modalFields").innerHTML=formHtml(type,item);if(type==="task")projectDeadlineGuard_();$("#entryModal").showModal();
}
async function saveModal(e){e.preventDefault();const formData=new FormData($("#entryForm")),data=Object.fromEntries(formData.entries()),{type,id}=state.editing||{};if(type==="task")data.supportMembers=formData.getAll("supportMembers").filter(n=>n!==data.owner).join("|");if(!type)return;const linkedProject=type==="task"?state.projects.find(p=>p.name===data.project):null;if(linkedProject?.deadline&&data.due>linkedProject.deadline){toast("タスク期限はプロジェクト期限を超えられません。");return;}
 const collection=type==="task"?state.tasks:type==="project"?state.projects:type==="member"?state.members:state.reports;
 const record=type==="task"?{id:id||"T-"+Date.now(),...data,plannedHours:Number(data.plannedHours||4)}:type==="project"?{id:id||"P-"+Date.now(),...data,progress:Number(data.progress||0)}:type==="member"?{id:id||"M-"+Date.now(),...data,capacity:Number(data.capacity||40),active:data.active!=="FALSE"}:{id:id||"R-"+Date.now(),...data};
 try{await post((id?"update":"create")+type[0].toUpperCase()+type.slice(1),record)}catch(err){handleApiError(err);return}
 $("#entryModal").close();state.editing=null;toast("保存しました。");await load()}
async function deleteItem(type,id){const name=(type==="task"?state.tasks:type==="project"?state.projects:state.members).find(x=>x.id===id)?.name||"この項目";if(!confirm("「"+name+"」を削除しますか？"))return;const key=type==="task"?"tasks":type==="project"?"projects":"members";try{await post("delete"+type[0].toUpperCase()+type.slice(1),{id})}catch(err){handleApiError(err);return}toast("削除しました。");await load()}
async function load(){try{const d=await jsonp("dashboard");if(d.ok===false){handleApiError(Object.assign(new Error(d.error),{code:d.code}));return}if(Array.isArray(d.tasks))state.tasks=d.tasks.map(x=>({id:x["Task ID"],name:x["Task Name"],project:x.Project,owner:x.Owner,due:fmt(x["Due Date"]),priority:x.Priority,status:x.Status,plannedHours:Number(x["Planned Hours"])||4,emergencyType:x["Emergency Type"],impact:x["Machine / Line / Impact"],completedAt:fmt(x["Completed At"]),supportMembers:x["Support Members"]||""}));if(Array.isArray(d.projects))state.projects=d.projects.map(x=>({id:x["Project ID"],name:x["Project Name"],leader:x.Leader,deadline:fmt(x.Deadline),progress:Number(x["Progress %"])||0,health:x.Health,desc:x["Objective / KPI"]}));if(Array.isArray(d.members))state.members=d.members.map(x=>({id:x["Member ID"],name:x.Name,email:x.Email,role:x.Role,capacity:Number(x["Capacity Hours / Week"])||40,active:String(x.Active)!=="FALSE"}));if(Array.isArray(d.reports))state.reports=d.reports.map(x=>({id:x["Report ID"],date:fmt(x["Work Date"]),memberEmail:x["Member Email"],member:state.members.find(m=>m.email===x["Member Email"])?.name||x["Member Email"],hours:Number(x["Work Hours"])||0,content:x["Work Details"],issues:x["Issues / Risks"],tomorrow:x["Tomorrow Plan"],taskId:x["Related Task ID"]||""}));renderAll()}catch(_){handleApiError(Object.assign(new Error("connection"),{code:"network"}))}}
window.openQpForm=(type,id,prefill)=>openForm(type,id,prefill);
document.addEventListener("DOMContentLoaded",()=>{$("#today").textContent=new Date().toLocaleDateString("ja-JP",{year:"numeric",month:"long",day:"numeric",weekday:"long"});renderAll();load();$("#languageToggle").onclick=()=>{state.language=state.language==="ja"?"en":"ja";$("#today").textContent=new Date().toLocaleDateString(state.language==="en"?"en-US":"ja-JP",{year:"numeric",month:"long",day:"numeric",weekday:"long"});renderAll()};$("#entryForm").addEventListener("submit",saveModal);function downloadCsv(filename,rows){const csv=rows.map(r=>r.map(v=>'"'+String(v??"").replaceAll('"','""')+'"').join(",")).join("\n"),a=document.createElement("a");a.href=URL.createObjectURL(new Blob(["\uFEFF"+csv],{type:"text/csv;charset=utf-8"}));a.download=filename;a.click();URL.revokeObjectURL(a.href)}const downloadWorkload=$("#downloadWorkload");if(downloadWorkload)downloadWorkload.onclick=()=>{const open=state.tasks.filter(t=>t.status!=="Done");downloadCsv("Q-Pulse_Workload.csv",[["Member","Capacity Hours/Week","Open Planned Hours","Load %"],...state.members.filter(m=>m.active!==false).map(m=>{const h=memberHours(m.name,open),cap=Number(m.capacity)||40;return [m.name,cap,Math.round(h*10)/10,Math.round(h/cap*100)+"%"]})])};const downloadReport=$("#downloadReport");if(downloadReport)downloadReport.onclick=()=>downloadCsv("Q-Pulse_Progress_Report.csv",[["Date","Member","Task","Hours","Progress / Issue"],...state.reports.map(r=>[r.date,r.member,state.tasks.find(t=>t.id===r.taskId)?.name||"",r.hours,r.content+(r.issues?" | Risk: "+r.issues:"")])]);Array.from(document.querySelectorAll("#cancelBtn,#cancelBtn2")).forEach(b=>b.onclick=()=>{$("#entryModal").close();state.editing=null});$("#taskSearch").oninput=renderTasks;$("#statusFilter").onchange=renderTasks;$$("[data-view]").forEach(b=>b.onclick=()=>{$$("[data-view]").forEach(x=>x.classList.remove("active"));b.classList.add("active");$$(".view").forEach(x=>x.classList.remove("active"));$("#"+b.dataset.view).classList.add("active")});$$("[data-new]").forEach(b=>b.onclick=()=>openForm(b.dataset.new));$("#saveReport").onclick=()=>openForm("report");});

/* ---------- UX: dropdown di daftar, detail project/member, laporan ---------- */
const STATUSES=["Not Started","In Progress","Done"];
function statusSelect(t){const cls=String(t.status).toLowerCase().replaceAll(" ","-");return "<select class='status-select "+esc(cls)+"' data-quick='task-status' data-id='"+esc(t.id)+"' title='状態を変更'>"+STATUSES.map(v=>"<option value='"+v+"'"+(v===t.status?" selected":"")+">"+esc(label("status",v))+"</option>").join("")+"</select>"}
function healthSelect(p){return "<select class='status-select "+(p.health==="At Risk"?"not-started":"done")+"' data-quick='project-health' data-id='"+esc(p.id)+"' title='健全性を変更'>"+["On Track","At Risk"].map(v=>"<option value='"+v+"'"+(v===(p.health||"On Track")?" selected":"")+">"+esc(label("health",v))+"</option>").join("")+"</select>"}
function projectTaskList(x){const pts=state.tasks.filter(t=>t.project===x.name);return "<details class='proj-tasks' "+(state.openProj.has(x.id)?"open":"")+" ontoggle=\"window.qpToggle('"+esc(x.id)+"',this.open)\"><summary>▸ タスク一覧・状態を更新（"+pts.length+"件）</summary>"+(pts.map(t=>"<div class='proj-task'><div><b>"+esc(t.name)+"</b><small>"+esc(t.owner)+" ・ "+esc(t.due)+" ・ "+(Number(t.plannedHours)||4)+"h</small></div>"+statusSelect(t)+"</div>").join("")||"<p class='muted'>まだタスクがありません。下のボタンで追加してください。</p>")+"<button class='text-btn' data-add-task data-project='"+esc(x.name)+"'>＋ このプロジェクトにタスクを追加</button></details>"}
window.qpToggle=(id,open)=>{open?state.openProj.add(id):state.openProj.delete(id)};
function showMemberDetail(name){state.detail=name;renderMemberDetail();$("#detailModal").showModal()}
function renderMemberDetail(){
 const m=state.members.find(x=>x.name===state.detail);if(!m)return;
 const mine=state.tasks.filter(t=>taskParticipants(t).includes(m.name)).sort((a,b)=>(a.status==="Done")-(b.status==="Done")||String(a.due).localeCompare(String(b.due)));
 const open=mine.filter(t=>t.status!=="Done"),h=memberHours(m.name,open),cap=Number(m.capacity)||40,pct=Math.min(100,Math.round(h/cap*100));
 const reports=state.reports.filter(r=>r.member===m.name||r.memberEmail===m.email).sort((a,b)=>String(b.date).localeCompare(String(a.date))).slice(0,5);
 $("#detailTitle").textContent=m.name+"　"+label("role",m.role);
 $("#detailBody").innerHTML="<div class='load-row'><span>現在の負荷（未完了の予定工数）</span><b>"+Math.round(h*10)/10+" / "+cap+" 時間（"+pct+"%）</b></div><div class='load-bar'><i class='"+(h>cap?"hot":"")+"' style='width:"+pct+"%'></i></div>"
 +"<div class='detail-actions'><b>担当タスク "+mine.length+"件（未完了 "+open.length+"）</b><button class='primary small' data-add-task data-owner='"+esc(m.name)+"'>＋ タスクを割り当て</button></div>"
 +"<div class='table-wrap'><table style='min-width:560px'><thead><tr><th>タスク / プロジェクト</th><th>期限</th><th>工数</th><th>役割</th><th>状態</th></tr></thead><tbody>"
 +(mine.map(t=>{const r=t.status==="Done"?{text:"完了",className:""}:remainingInfo(t.due);return "<tr><td><b>"+esc(t.name)+"</b><br><small>"+esc(t.project)+"</small></td><td>"+esc(t.due)+"<br><small class='"+r.className+"'>"+esc(r.text)+"</small></td><td>"+(Number(t.plannedHours)||4)+"h</td><td>"+(t.owner===m.name?"主担当":"支援")+"</td><td>"+statusSelect(t)+"</td></tr>"}).join("")||"<tr><td colspan='5'>担当タスクはありません。</td></tr>")+"</tbody></table></div>"
 +"<h3 style='margin:18px 0 8px'>最近の進捗メモ</h3>"+(reports.map(r=>"<p class='detail-note'><b>"+esc(r.date)+"</b>　"+esc(r.content||"—")+(r.issues&&r.issues!=="なし"?"<br><small class='risk-line'>⚑ "+esc(r.issues)+"</small>":"")+"</p>").join("")||"<p class='muted'>メモはまだありません。</p>");
}
function qpCsv(filename,rows){const csv=rows.map(r=>r.map(v=>'"'+String(v??"").replaceAll('"','""')+'"').join(",")).join("\n"),a=document.createElement("a");a.href=URL.createObjectURL(new Blob(["﻿"+csv],{type:"text/csv;charset=utf-8"}));a.download=filename;a.click();URL.revokeObjectURL(a.href)}
function projectReport(){const rows=[["Project","Leader","Deadline","Progress %","Health","Task","Owner","Support","Due","Planned h","Status","Completed"]];state.projects.forEach(p=>{const base=[p.name,p.leader,p.deadline,projectProgress(p),p.health],ts=state.tasks.filter(t=>t.project===p.name);if(!ts.length)rows.push([...base,"","","","","","",""]);ts.forEach(t=>rows.push([...base,t.name,t.owner,String(t.supportMembers||"").replaceAll("|",", "),t.due,Number(t.plannedHours)||4,t.status,t.completedAt||""]))});qpCsv("Q-Pulse_Project_Report_"+fmt(new Date())+".csv",rows)}
function memberReport(){const todayStr=fmt(new Date());const rows=[["Member","Role","Capacity h/week","Open planned h","Load %","Done tasks","Open tasks","Overdue open tasks","On-time %","Notes"]];state.members.filter(m=>m.active!==false).forEach(m=>{const mine=state.tasks.filter(t=>taskParticipants(t).includes(m.name)),done=mine.filter(t=>t.status==="Done"),open=mine.filter(t=>t.status!=="Done"),h=memberHours(m.name,open),cap=Number(m.capacity)||40,timed=done.filter(t=>t.completedAt&&t.due),ont=timed.filter(t=>t.completedAt<=t.due).length;rows.push([m.name,m.role,cap,Math.round(h*10)/10,Math.round(h/cap*100),done.length,open.length,open.filter(t=>t.due&&t.due<todayStr).length,timed.length?Math.round(ont/timed.length*100):"",state.reports.filter(r=>r.member===m.name||r.memberEmail===m.email).length])});qpCsv("Q-Pulse_Member_Report_"+todayStr+".csv",rows)}
document.addEventListener("change",async e=>{
 const el=e.target.closest&&e.target.closest("[data-quick]");if(!el)return;
 const kind=el.dataset.quick,id=el.dataset.id;let type,item;
 if(kind==="task-status"){type="Task";item=state.tasks.find(t=>t.id===id);if(item)item.status=el.value}
 else if(kind==="project-health"){type="Project";item=state.projects.find(p=>p.id===id);if(item)item.health=el.value}
 if(!item)return;renderAll();
 try{await post("update"+type,{...item});toast("更新しました。")}catch(err){handleApiError(err)}
 await load()});
document.addEventListener("click",e=>{
 const add=e.target.closest&&e.target.closest("[data-add-task]");
 if(add){const d=$("#detailModal");if(d&&d.open)d.close();openForm("task",null,{project:add.dataset.project,owner:add.dataset.owner});return}
 const det=e.target.closest&&e.target.closest("[data-member-detail]");
 if(det){showMemberDetail(det.dataset.memberDetail);return}
 if(e.target.closest&&e.target.closest("[data-print]")){window.print();return}
 if(e.target.id==="projectReportBtn")projectReport();
 if(e.target.id==="memberReportBtn")memberReport()});
